M48
; DRILL file {KiCad (6.0.5)} date Fri Aug 18 19:40:01 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-08-18T19:40:01-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.100
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.000
%
G90
G05
T1
X135.877Y-104.73
T2
X79.081Y-120.343
X91.741Y-120.343
T3
X74.782Y-83.14
X134.757Y-82.83
T0
M30
